import { execFile } from "node:child_process";
import { mkdtemp, rm, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import path from "node:path";
import { promisify } from "node:util";
import { describe, expect, it } from "vitest";
import {
  getMarkdownSection,
  normalizeWhitespace,
  readRepoFile,
  readSkillSource,
} from "../__test-helpers__/skill-contracts.js";

const execFileAsync = promisify(execFile);

function quoteShellArg(value: string): string {
  return `"${value.replaceAll("\\", "\\\\").replaceAll('"', '\\"')}"`;
}

function nodeNoopCommand(): string {
  return `${quoteShellArg(process.execPath)} -e "process.exit(0)"`;
}

function sliceBetween(content: string, start: string, end: string): string {
  const startIndex = content.indexOf(start);
  const endIndex = content.indexOf(end);

  expect(startIndex).toBeGreaterThanOrEqual(0);
  expect(endIndex).toBeGreaterThan(startIndex);

  return content.slice(startIndex, endIndex);
}

function expectSharedLifecycleReference(section: string): void {
  expect(section).toContain("subagent-lifecycle");
  expect(section).toContain("target-honest cleanup outcomes");
  expect(section).toContain("slot-limit");
  expect(section).toContain("recovery");
}

async function git(args: string[], cwd: string): Promise<void> {
  await execFileAsync("git", args, { cwd });
}

async function createAutosquashFixture(
  squashSubject = "squash! feat: update note",
): Promise<string> {
  const repoDir = await mkdtemp(path.join(tmpdir(), "devcanon-autosquash-"));

  await git(["init", "-q"], repoDir);
  await git(["checkout", "-q", "-b", "main"], repoDir);
  await git(["config", "user.name", "DevCanon Test"], repoDir);
  await git(["config", "user.email", "devcanon@example.test"], repoDir);
  await git(["config", "commit.gpgSign", "false"], repoDir);

  await writeFile(path.join(repoDir, "note.txt"), "base\n", "utf-8");
  await git(["add", "note.txt"], repoDir);
  await git(["commit", "-q", "-m", "feat: base"], repoDir);

  await git(["checkout", "-q", "-b", "feature/autosquash"], repoDir);
  await writeFile(path.join(repoDir, "note.txt"), "base\nfeature\n", "utf-8");
  await git(["add", "note.txt"], repoDir);
  await git(["commit", "-q", "-m", "feat: update note"], repoDir);

  await writeFile(
    path.join(repoDir, "note.txt"),
    "base\nfeature\nsquash follow-up\n",
    "utf-8",
  );
  await git(["add", "note.txt"], repoDir);
  await git(["commit", "-q", "-m", squashSubject], repoDir);

  return repoDir;
}

describe("existing skills source prose contracts", () => {
  it("keeps generated/reference coverage triggers owned by the skill writing guideline", async () => {
    const guideline = await readRepoFile("docs/guidelines/writing-skills.md");
    const coverageRule = getMarkdownSection(
      guideline,
      "8. Generated/Reference Coverage Trigger",
    );
    const normalizedRule = normalizeWhitespace(coverageRule).toLowerCase();

    for (const phrase of [
      "source-contract",
      "src/skill-contracts/",
      "render",
      "src/render/",
      "scripts",
      "target metadata",
      "sidecars",
      "touched-skill allowlists",
      "generated output",
      "disposable",
    ]) {
      expect(normalizedRule).toContain(phrase);
    }

    expect(normalizedRule).toMatch(/skill\.md.*prose|prose.*skill\.md/);
    expect(normalizedRule).toMatch(
      /references\/.*mirrored|mirrored.*references\//,
    );
    expect(normalizedRule).toMatch(/scripts\/.*runtime|runtime.*scripts\//);
    expect(normalizedRule).toContain("do not snapshot every generated byte");
  });

  it("keeps DevCanon issue reporting pointed at the DevCanon repository", async () => {
    const skillSource = await readSkillSource("report-devcanon-issue");

    expect(skillSource).toContain("name: report-devcanon-issue");
    expect(skillSource).toContain("ryumiel/devcanon");
    expect(skillSource).not.toContain("ryumiel/agent-manager");
    expect(skillSource).toContain("consumer repo names, owners, orgs");
    expect(skillSource).toContain("Ask one question at a time");
    expect(skillSource).toContain(
      "Never post an issue without showing the exact draft first and receiving explicit confirmation.",
    );
    expect(skillSource).toContain("MODE=draft");
    expect(skillSource).toContain(
      "If GitHub access to `ryumiel/devcanon` is unavailable, return `MODE=draft` and stop without attempting to post.",
    );
  });

  it("keeps behavior-spec evidence routing owned by durable guideline sources", async () => {
    const procedureMap = await readRepoFile(
      "docs/guidelines/portable-afds-user-procedure-map.md",
    );
    const routingGuideline = await readRepoFile(
      "docs/guidelines/behavior-spec-evidence-routing.md",
    );

    expect(procedureMap).toContain("behavior-spec-evidence-routing.md");
    expect(procedureMap).toContain("durable source of origin");
    expect(procedureMap).toContain(
      "`spec-readiness-review`, then `issue-slicing`",
    );

    expect(routingGuideline).toContain("The durable source of origin");
    expect(routingGuideline).toContain(
      "`docs/specs/afds-workflow-routing.md` `EVID-001`",
    );
    expect(routingGuideline).toContain("Runtime excerpt from `EVID-001`");
    expect(routingGuideline).toContain(
      "checked requirement, route, execution contract, or owner",
    );
    expect(routingGuideline).toContain("blocker or follow-up owner");
    expect(routingGuideline).toContain("contract to behavior-spec authoring");

    for (const section of [
      "Evidence Pointers",
      "Readiness Before Slicing",
      "Storage Boundary",
    ]) {
      expect(routingGuideline).toContain(section);
    }
  });

  it("keeps the spec-readiness-review status and owner-link contract in source", async () => {
    const skillSource = await readSkillSource("spec-readiness-review");
    const reviewProcedure = getMarkdownSection(skillSource, "Review Procedure");
    const outputFormat = getMarkdownSection(skillSource, "Output Format");

    expect(outputFormat).toContain(
      "**Status:** <one of: Ready, Needs revision, Blocked>",
    );
    expect(outputFormat).toContain(
      "Final status: <repeat the same single status>",
    );
    expect(outputFormat).not.toContain(
      "**Status:** Ready | Needs revision | Blocked",
    );
    expect(outputFormat).not.toContain(
      "Final status: Ready | Needs revision | Blocked",
    );

    expect(reviewProcedure).toContain(
      "references/pre-slicing-procedure-map.md",
    );
    expect(reviewProcedure).toContain("references/routing-and-evidence.md");
    expect(reviewProcedure).toContain(
      "artifact, durable team, system, or role",
    );
    expect(reviewProcedure).toContain("do not accept");
    expect(reviewProcedure).toContain("person names, assignees");
    expect(reviewProcedure).toContain("live tracker ownership");
    expect(reviewProcedure).toContain("Repo-local project docs are optional");
    expect(reviewProcedure).toContain(
      "Do not treat repo-local docs as required",
    );
    expect(skillSource).toContain("does not approve implementation");

    expect(skillSource).not.toContain("docs/specs/afds-workflow-routing.md");
    expect(skillSource).not.toContain("MAP.md");
    expect(skillSource).not.toContain("docs/guidelines/");
  });

  it("keeps the issue-slicing draft-only provider-neutral contract in source", async () => {
    const skillSource = await readSkillSource("issue-slicing");
    const procedure = getMarkdownSection(skillSource, "Procedure");
    const evidencePointers = getMarkdownSection(
      skillSource,
      "Evidence Pointers",
    );
    const outputFormat = getMarkdownSection(skillSource, "Output Format");

    expect(outputFormat).toContain("MODE=draft");
    expect(outputFormat).toContain("MODE=blocked");
    expect(skillSource).toContain("GitHub Issues or Linear");
    expect(procedure).toContain(
      "docs/guidelines/portable-afds-user-procedure-map.md",
    );

    for (const forbiddenMutation of [
      "Do not create live issues",
      "assign users",
      "set status",
      "mutate labels",
      "duplicate live tracker state",
    ]) {
      expect(skillSource).toContain(forbiddenMutation);
    }

    expect(evidencePointers).toContain(
      "At least one evidence pointer must name the owning durable artifact",
    );
    expect(skillSource).toContain(
      "<owning durable artifact>: <stable reference>",
    );
    expect(outputFormat).not.toContain(
      "Final mode: <repeat MODE=draft or MODE=blocked>",
    );
  });

  it("keeps the write-product-requirements PRD boundaries in source", async () => {
    const skillSource = await readSkillSource("write-product-requirements");
    const overview = getMarkdownSection(skillSource, "Overview");
    const procedure = getMarkdownSection(skillSource, "Procedure");
    const shape = getMarkdownSection(skillSource, "Product Requirements Shape");
    const boundaryChecklist = getMarkdownSection(
      skillSource,
      "Boundary Checklist",
    );

    expect(procedure).toContain("docs/product-requirements/<topic>.md");
    expect(procedure).toContain("profile gate");
    expect(overview).toContain("product intent");
    expect(skillSource).toContain("live issue state");
    expect(procedure).toContain("PR state");
    expect(procedure).toContain("agent-local execution detail");
    expect(boundaryChecklist).toContain("contract authority");
    expect(boundaryChecklist).toContain("links to contract authority");
    expect(boundaryChecklist).toContain("source-owned schemas");
    expect(shape).toContain("Readiness criteria");
    expect(shape).toContain("Product validation criteria");
    expect(shape).toContain("Expected follow-up artifact references");
    expect(shape).toContain("Non-goals and out-of-scope items");
    expect(skillSource).toContain("immediate next owning artifact");
    expect(procedure).toContain("Portable AFDS Toolkit PRD");
    expect(procedure).toContain("root `PRD.md`");
    expect(shape).toContain("Stable requirement IDs");
    expect(shape).toContain("line-number references");
    expect(procedure).toContain("write-product-spec");
    expect(procedure).toContain("docs/specs/<topic>.md");
  });

  it("keeps guarded tiny-diff review routing constraints in play-review source", async () => {
    const skillSource = await readSkillSource("play-review");
    const tinyDiffSection = getMarkdownSection(
      skillSource,
      "Phase 2.75: Guarded tiny-diff mode",
    );
    const redFlags = await readRepoFile(
      "skills/play-review/references/red-flags.md",
    );

    for (const phrase of [
      "Guarded tiny-diff mode",
      "at most 2 files",
      "at most 20 total lines",
      "Correctness, Data-safety, and critic verification remain",
      "safe tiny diff example",
      "Result: tiny-diff mode may suppress the",
      "dynamic fanout; Correctness, Data-safety, and critic still run.",
      "small-but-risky diff example",
      "Result: normal full dynamic fanout",
      "If any check is ambiguous, fall back to the normal full dynamic fanout.",
      "`is_followup_narrow` is **false**",
      "docs/specs/**",
      "reviewer-routing policy",
      "docs/guidelines/*.md",
      "references/red-flags.md",
    ]) {
      expect(tinyDiffSection).toContain(phrase);
    }

    expect(tinyDiffSection).not.toContain("skills/**/SKILL.md");
    expect(redFlags).toContain(
      "You treated line count alone as enough to suppress the dynamic fanout",
    );
  });

  it("keeps review-response commit continuity policy in source", async () => {
    const skillSource = await readSkillSource("play-review-response");
    const implementationOrderIndex = skillSource.indexOf(
      "## Implementation Order",
    );
    const commitPolicyIndex = skillSource.indexOf(
      "## PR Branch Commit Continuity",
    );
    const threadClosureIndex = skillSource.indexOf(
      "## Pushed-Fix Inline Thread Closure",
    );
    const pushBackIndex = skillSource.indexOf("## When To Push Back");

    expect(implementationOrderIndex).toBeGreaterThanOrEqual(0);
    expect(commitPolicyIndex).toBeGreaterThan(implementationOrderIndex);
    expect(threadClosureIndex).toBeGreaterThan(commitPolicyIndex);
    expect(pushBackIndex).toBeGreaterThan(threadClosureIndex);

    const implementationOrder = getMarkdownSection(
      skillSource,
      "Implementation Order",
    );
    const commitPolicy = getMarkdownSection(
      skillSource,
      "PR Branch Commit Continuity",
    );
    const normalizedCommitPolicy = normalizeWhitespace(commitPolicy);
    const threadClosure = getMarkdownSection(
      skillSource,
      "Pushed-Fix Inline Thread Closure",
    );
    const normalizedThreadClosure = normalizeWhitespace(threadClosure);
    const githubReplies = getMarkdownSection(
      skillSource,
      "GitHub Thread Replies",
    );
    const normalizedGithubReplies = normalizeWhitespace(githubReplies);

    expect(normalizeWhitespace(implementationOrder)).toMatch(
      /verification.*already-pushed or reviewed PR branch.*follow-up commit.*plain push/,
    );

    expect(normalizedCommitPolicy).toMatch(
      /pushed.*review.*follow-up commit.*plain push/i,
    );
    expect(normalizedCommitPolicy).toMatch(/do not amend.*do not force-push/i);
    expect(normalizedCommitPolicy).toMatch(
      /user explicitly asks.*repository workflow/i,
    );
    expect(normalizedCommitPolicy).toMatch(/pre-push.*cleanup.*allowed/i);
    expect(normalizedCommitPolicy).toMatch(
      /```text.*pre-push.*amend.*post-review.*force.*post-review.*follow-up commit.*```/i,
    );
    expect(normalizedCommitPolicy).toContain("review continuity");

    expect(normalizedThreadClosure).toMatch(
      /verify.*current review comments.*implement.*run.*checks.*commit.*push.*re-fetch.*thread state.*confirm.*github writes.*reply in-thread.*re-fetch.*thread state.*resolve.*eligible threads/i,
    );
    expect(normalizedThreadClosure).toMatch(
      /re-fetch.*after.*push.*before.*reply/i,
    );
    expect(normalizedThreadClosure).toMatch(
      /re-fetch.*after.*reply.*immediately before.*resolution/i,
    );
    expect(normalizedThreadClosure).toContain("Safe-to-resolve criteria");

    for (const requiredCriterion of [
      "GitHub writes are permitted",
      "explicit user approval",
      "approved posting gate",
      "latest fetched thread after the reply is still unresolved",
      "same concern",
      "pushed branch contains the fix",
      "reply explains why no code change is required",
      "relevant checks",
      "permission to resolve",
      "active owner",
    ]) {
      expect(normalizedThreadClosure).toContain(requiredCriterion);
    }

    for (const requiredDisposition of [
      "Explanation-only",
      "post-reply fetched thread",
      "Stale or outdated",
      "Already-resolved",
      "unclear, partially fixed, or newly conflicting",
      "stay unresolved",
    ]) {
      expect(normalizedThreadClosure).toContain(requiredDisposition);
    }

    expect(normalizedGithubReplies).toMatch(/comment thread/i);
    expect(normalizedGithubReplies).toMatch(/follow-up commit or fix/i);
    expect(normalizedGithubReplies).toMatch(/thread context/i);
    expect(normalizedGithubReplies).toContain(
      "Pushed-Fix Inline Thread Closure",
    );
  });

  it("keeps pr-merge final reports separate from local cleanup outcomes", async () => {
    const skillSource = await readSkillSource("pr-merge");
    const cleanupSection = getMarkdownSection(
      skillSource,
      "Step 3b: Post-Merge Cleanup",
    );
    const normalizedCleanupSection = normalizeWhitespace(cleanupSection);

    expect(cleanupSection).toContain("Final report contract");
    expect(normalizedCleanupSection).toMatch(/remote merge.*PR URL.*cleanup/i);
    expect(normalizedCleanupSection).toMatch(
      /worktree.*removed, skipped, or failed.*path.*reason/i,
    );
    expect(normalizedCleanupSection).toMatch(/base checkout\/pull.*attempted/i);
    expect(normalizedCleanupSection).toMatch(
      /local branch.*deleted, retained, or skipped.*reason/i,
    );
    expect(normalizedCleanupSection).toMatch(/manual cleanup.*required.*none/i);
    expect(normalizedCleanupSection).not.toContain(
      "Report the merge to the user with the PR URL. Done.",
    );
  });

  it("keeps play-branch-finish autosquash local, opt-in, and PR-body neutral", async () => {
    const skillSource = await readSkillSource("play-branch-finish");
    const option2 = sliceBetween(
      skillSource,
      "#### Option 2: Push and Create PR",
      "#### Option 3: Keep As-Is",
    );
    const normalizedOption2 = normalizeWhitespace(option2);
    const redFlags = await readRepoFile(
      "skills/play-branch-finish/references/red-flags.md",
    );
    const commonMistakes = await readRepoFile(
      "skills/play-branch-finish/references/common-mistakes.md",
    );

    expect(skillSource).toContain("Present exactly these 4 options");
    expect(normalizedOption2).toContain(
      "Optional pre-push autosquash checkpoint",
    );
    expect(normalizedOption2).toMatch(
      /after tests pass.*base branch.*resolved.*before.*git push/i,
    );
    expect(normalizedOption2).toContain(
      "git log --oneline <base-branch>..HEAD",
    );
    expect(normalizedOption2).toContain("fixup!");
    expect(normalizedOption2).toContain("squash!");
    expect(normalizedOption2).toMatch(
      /opt-in.*never.*default.*exact affirmative/i,
    );
    expect(normalizedOption2).toContain(
      "This rewrites only local feature-branch commits and is not required.",
    );
    expect(normalizedOption2).toContain(
      "AUTOSQUASH_BASE=$(git merge-base <base-branch> HEAD)",
    );
    expect(normalizedOption2).toContain("PRE_AUTOSQUASH_HEAD=");
    expect(normalizedOption2).toContain('test -z "$(git status --porcelain)"');
    expect(normalizedOption2).toContain(
      'GIT_SEQUENCE_EDITOR=: GIT_EDITOR=: git rebase -i --autosquash "$AUTOSQUASH_BASE"',
    );
    expect(normalizedOption2).toContain("git rebase --abort");
    expect(normalizedOption2).toContain(
      'git reset --hard "$PRE_AUTOSQUASH_HEAD"',
    );
    expect(normalizedOption2).toContain("REMAINING_AUTOSQUASH_MARKERS=");
    expect(normalizedOption2).toContain(
      'git log --format=%s "$AUTOSQUASH_BASE"..HEAD',
    );
    expect(normalizedOption2).toMatch(/fixup!.*squash!|squash!.*fixup!/i);
    expect(normalizedOption2).toMatch(
      /post-autosquash tree.*unchanged.*before push/i,
    );
    expect(normalizedOption2).toMatch(
      /shared.*already-pushed.*open PR.*reviewed.*non-local/i,
    );
    expect(normalizedOption2).toMatch(
      /separate.*explicit shared-branch rewrite approval/i,
    );
    expect(normalizedOption2).toMatch(/granular.*review\/audit value.*skip/i);
    expect(normalizedOption2).toMatch(
      /PR (title and description|body).*final-state oriented/i,
    );
    expect(normalizedOption2).toContain("commit-history narration");

    expect(normalizedOption2).not.toMatch(
      /autosquash[^.]{0,80}(reduces?|improves?)[^.]{0,80}branch-review/i,
    );
    expect(normalizedOption2).not.toMatch(
      /branch-review[^.]{0,80}(cost|efficiency)/i,
    );

    expect(redFlags).toMatch(/autosquash/i);
    expect(redFlags).toMatch(/shared|already-pushed|open PR|reviewed/i);
    expect(redFlags).toMatch(/audit/i);
    expect(commonMistakes).toMatch(/autosquash/i);
    expect(commonMistakes).toMatch(/unchanged tree|tree.*unchanged/i);
    expect(commonMistakes).toMatch(/commit-history narration/i);
  });

  it("keeps the documented autosquash command noninteractive for squash markers", async () => {
    const repoDir = await createAutosquashFixture();
    const editorCommand = nodeNoopCommand();

    try {
      const { stdout: mergeBase } = await execFileAsync(
        "git",
        ["merge-base", "main", "HEAD"],
        { cwd: repoDir },
      );
      const { stdout: preTree } = await execFileAsync(
        "git",
        ["rev-parse", "HEAD^{tree}"],
        { cwd: repoDir },
      );

      await execFileAsync(
        "git",
        ["rebase", "-i", "--autosquash", mergeBase.trim()],
        {
          cwd: repoDir,
          env: {
            ...process.env,
            GIT_SEQUENCE_EDITOR: editorCommand,
            GIT_EDITOR: editorCommand,
          },
        },
      );

      const { stdout: postTree } = await execFileAsync(
        "git",
        ["rev-parse", "HEAD^{tree}"],
        { cwd: repoDir },
      );
      const { stdout: log } = await execFileAsync(
        "git",
        ["log", "--oneline", "main..HEAD"],
        { cwd: repoDir },
      );

      expect(postTree.trim()).toBe(preTree.trim());
      expect(log).not.toContain("squash!");
      expect(log.trim().split("\n")).toHaveLength(1);
    } finally {
      await rm(repoDir, { force: true, recursive: true });
    }
  });

  it("keeps unmatched autosquash markers detectable after rebase", async () => {
    const repoDir = await createAutosquashFixture("squash! feat: base");
    const editorCommand = nodeNoopCommand();

    try {
      const { stdout: mergeBase } = await execFileAsync(
        "git",
        ["merge-base", "main", "HEAD"],
        { cwd: repoDir },
      );

      await execFileAsync(
        "git",
        ["rebase", "-i", "--autosquash", mergeBase.trim()],
        {
          cwd: repoDir,
          env: {
            ...process.env,
            GIT_SEQUENCE_EDITOR: editorCommand,
            GIT_EDITOR: editorCommand,
          },
        },
      );

      const { stdout: remainingMarkers } = await execFileAsync(
        "git",
        ["log", "--format=%s", `${mergeBase.trim()}..HEAD`],
        { cwd: repoDir },
      );

      expect(remainingMarkers).toContain("squash! feat: base");
    } finally {
      await rm(repoDir, { force: true, recursive: true });
    }
  });

  it("keeps subagent-lifecycle references in direct spawning workflow sources", async () => {
    const issuePrimingWorkflow = await readSkillSource(
      "issue-priming-workflow",
    );
    const playReview = await readSkillSource("play-review");
    const playPlanning = await readSkillSource("play-planning");
    const playAgentDispatch = await readSkillSource("play-agent-dispatch");
    const playSkillAuthoring = await readSkillSource("play-skill-authoring");
    const prMerge = await readSkillSource("pr-merge");

    const issueLifecycleSection = sliceBetween(
      issuePrimingWorkflow,
      "## Subagent Lifecycle",
      "## Phase 2: Complexity Gate",
    );
    expectSharedLifecycleReference(issueLifecycleSection);
    expect(issueLifecycleSection).toContain(
      "Before dispatching the Phase 2 gate agent",
    );
    expect(issueLifecycleSection).toContain("Phase 3 research agent");
    expect(normalizeWhitespace(issueLifecycleSection)).toContain("gate result");
    expect(issueLifecycleSection).toContain("research brief path");

    const issuePhase6Section = sliceBetween(
      issuePrimingWorkflow,
      "### Phase 6: Implement",
      "### Phase 7: Branch Review",
    );
    expect(issuePhase6Section).toContain("subagent-lifecycle");
    expect(issuePhase6Section).toContain(
      "Before the Phase 6 handoff, run the `subagent-lifecycle` cleanup gate",
    );
    expect(issuePhase6Section.indexOf("`subagent-lifecycle`")).toBeLessThan(
      issuePhase6Section.indexOf("Invoke `play-subagent-execution`"),
    );

    const playReviewPhase3Section = sliceBetween(
      playReview,
      "## Phase 3: Spawn agents",
      "**Core agents (always spawned):**",
    );
    expectSharedLifecycleReference(playReviewPhase3Section);
    expect(playReviewPhase3Section).toContain(
      "Before spawning Phase 3 reviewer agents",
    );
    expect(playReviewPhase3Section).toContain("review scope");
    expect(playReviewPhase3Section).toContain("concrete findings");
    expect(playReviewPhase3Section).toContain(
      "Critic verdicts are captured with the critic session in Phase 5",
    );

    const playReviewCriticSection = sliceBetween(
      playReview,
      "## Phase 5: Critic verification",
      "## Hard Rules",
    );
    expect(playReviewCriticSection).toContain("subagent-lifecycle");
    expect(playReviewCriticSection).toContain(
      "Before spawning the critic agent, run the `subagent-lifecycle` cleanup gate",
    );
    expect(playReviewCriticSection).toContain("critic report");
    expect(playReviewCriticSection).toContain("verdicts");

    const playPlanningReviewSection = sliceBetween(
      playPlanning,
      "## Plan Review",
      "## Execution Handoff",
    );
    expectSharedLifecycleReference(playPlanningReviewSection);
    expect(playPlanningReviewSection).toContain(
      "Before dispatching the plan-review agent",
    );
    expect(playPlanningReviewSection).toContain("PASS/FAIL result");
    expect(playPlanningReviewSection).toContain("specific gaps");

    const playAgentDispatchSection = sliceBetween(
      playAgentDispatch,
      "### 3. Dispatch in Parallel",
      "## Agent Prompt Structure",
    );
    const normalizedPlayAgentDispatchSection = normalizeWhitespace(
      playAgentDispatchSection,
    );
    expectSharedLifecycleReference(playAgentDispatchSection);
    expect(playAgentDispatchSection).toContain("Before parallel dispatch");
    expect(playAgentDispatchSection).toContain(
      "one pending ledger row per planned agent",
    );
    expect(normalizedPlayAgentDispatchSection).toContain(
      "Update the `subagent-lifecycle` ledger with each returned session's role-specific state before closing or superseding it",
    );
    expect(normalizedPlayAgentDispatchSection).toContain(
      "After each returned session is integrated, run the `subagent-lifecycle` cleanup gate before keeping or spawning any additional agent sessions",
    );

    const playSkillAuthoringSection = sliceBetween(
      playSkillAuthoring,
      "## Overview",
      "## What is a Skill?",
    );
    const normalizedPlaySkillAuthoringSection = normalizeWhitespace(
      playSkillAuthoringSection,
    );
    expectSharedLifecycleReference(playSkillAuthoringSection);
    expect(normalizedPlaySkillAuthoringSection).toContain(
      "When dispatching pressure-scenario subagents",
    );
    expect(normalizedPlaySkillAuthoringSection).toContain(
      "Capture each pressure-scenario subagent's prompt, baseline/pass result, observed rationalizations, and pressure conditions before closing or superseding the session",
    );

    const prMergeInvestigationSection = sliceBetween(
      prMerge,
      "### 4b. Dispatch investigation agent",
      '### 4c. "In scope" definition',
    );
    expectSharedLifecycleReference(prMergeInvestigationSection);
    expect(prMergeInvestigationSection).toContain(
      "Before dispatching the CI investigation agent",
    );
    expect(prMergeInvestigationSection).toContain("CI run/check identifiers");
    expect(normalizeWhitespace(prMergeInvestigationSection)).toContain(
      "in-scope/out-of-scope classification",
    );
  });

  it("keeps bundled prompt and runtime-reference prose contracts in source", async () => {
    const implementerPrompt = await readRepoFile(
      "skills/play-subagent-execution/references/implementer-prompt.md",
    );
    const mechanicalImplementerPrompt = await readRepoFile(
      "skills/play-subagent-execution/references/mechanical-implementer-prompt.md",
    );
    const specReviewerPrompt = await readRepoFile(
      "skills/play-subagent-execution/references/spec-reviewer-prompt.md",
    );
    const writeProductSpecRouting = await readRepoFile(
      "skills/write-product-spec/references/behavior-spec-evidence-routing.md",
    );
    const researchPrompt = await readRepoFile(
      "skills/issue-priming-workflow/references/research-agent-prompt.md",
    );

    expect(implementerPrompt).toContain(
      "If the task includes a contract checklist",
    );
    expect(normalizeWhitespace(implementerPrompt)).toContain(
      "owner/authority, affected consumers/generated outputs, must-preserve, required behavior",
    );
    expect(normalizeWhitespace(implementerPrompt)).toContain(
      "source-of-truth, consumer, generated-output, or evidence surface that source inspection cannot confirm",
    );
    expect(implementerPrompt).toContain(
      "helper-name prescriptions, line-number edits, or commit recipes",
    );

    expect(mechanicalImplementerPrompt).toContain(
      "helper-name prescriptions, line-number edits, or commit recipes",
    );
    expect(mechanicalImplementerPrompt).toContain(
      "affected consumers/generated outputs, must-preserve, required behavior",
    );
    expect(mechanicalImplementerPrompt).toContain(
      "Read the relevant source files, existing docs, ADRs, helpers, generated",
    );
    expect(normalizeWhitespace(mechanicalImplementerPrompt)).toContain(
      "A blank checklist field, unexplained `N/A`, or unconfirmed owner/authority",
    );
    expect(normalizeWhitespace(mechanicalImplementerPrompt)).toContain(
      "source-of-truth, consumer, generated-output, or evidence surface is not a mechanical replacement target",
    );

    expect(specReviewerPrompt).toContain(
      "**Task contract checklist (when present in the requested task):**",
    );
    expect(specReviewerPrompt).toContain(
      "Verify owner/authority fields against the source files, docs, ADRs",
    );
    expect(specReviewerPrompt).toContain(
      "Verify affected consumers and generated outputs named by the task",
    );
    expect(specReviewerPrompt).toContain(
      "Verify risk surfaces and proof obligations were addressed",
    );

    expect(writeProductSpecRouting).toContain("packaged runtime reference");
    expect(writeProductSpecRouting).toContain("minimum evidence pointer");
    expect(writeProductSpecRouting).toContain(
      "durable team, system, role, or artifact",
    );
    expect(writeProductSpecRouting).not.toContain(
      "docs/guidelines/behavior-spec-evidence-routing.md",
    );
    expect(writeProductSpecRouting).not.toContain(
      "docs/specs/afds-workflow-routing.md",
    );
    expect(writeProductSpecRouting).not.toContain("EVID-001");
    expect(writeProductSpecRouting).not.toContain("source of origin");

    const normalizedResearchPrompt = normalizeWhitespace(researchPrompt);
    expect(researchPrompt).toContain("subagent-lifecycle");
    for (const phrase of [
      "Before dispatching internal research sub-agents",
      "target capability",
      "cleanup gate before spawns",
      "target-honest cleanup outcomes",
      "slot-limit recovery",
      "role-specific state",
      "scope",
      "report",
      "source references",
      "blocker state",
    ]) {
      expect(normalizedResearchPrompt).toContain(phrase);
    }
  });
});
