import path from "node:path";
import type {
  ManagedRecord,
  Manifest,
  ManifestBoundary,
  ResolvedConfig,
} from "../config/schema.js";

export class ManifestIdentityError extends Error {
  constructor(message: string) {
    super(message);
    this.name = "ManifestIdentityError";
  }
}

export type ManagedRecordOwnership = "owned" | "foreign";

export interface ManagedRecordClassification {
  ownership: ManagedRecordOwnership;
  name: string;
  home: string;
  expectedDestination: string;
}

export interface NormalizedManifestIdentity {
  manifest: Manifest;
  boundary: ManifestBoundary;
  records: ManagedRecordClassification[];
}

/**
 * Return the canonical, lexical installation boundary. This deliberately does
 * not resolve symlinks: configured homes may not exist yet and identity is
 * defined by the configured path tuple, not by a filesystem observation.
 */
export function normalizeManifestBoundary(
  config: ResolvedConfig,
): ManifestBoundary {
  return {
    claudeSkillsHome: path.resolve(config.targets.claude.skillsHome),
    claudeAgentsHome: path.resolve(config.targets.claude.agentsHome),
    codexSkillsHome: path.resolve(config.targets.codex.skillsHome),
    codexAgentsHome: path.resolve(config.targets.codex.agentsHome),
  };
}

export function assertManifestBoundaryMatches(
  boundary: ManifestBoundary,
  expectedBoundary: ManifestBoundary,
): void {
  for (const key of Object.keys(expectedBoundary) as Array<
    keyof ManifestBoundary
  >) {
    if (boundary[key] !== expectedBoundary[key]) {
      throw new ManifestIdentityError(
        `Manifest boundary mismatch for ${key}: expected ${expectedBoundary[key]}, found ${boundary[key]}`,
      );
    }
  }
}

/**
 * Classify a record using the entire target/type/name/home/destination tuple.
 * A record is owned only when its installed path is the exact direct child
 * generated by the target renderer convention. Filesystem presence is
 * intentionally not part of this decision.
 */
export function classifyManagedRecord(
  record: ManagedRecord,
  boundary: ManifestBoundary,
): ManagedRecordClassification {
  const home = targetHome(record, boundary);
  assertNoTraversalSegments(record.installedPath);
  const name = record.name ?? deriveLegacyRecordName(record, home);
  assertRecordName(name, record);

  const expectedDestination = path.join(home, renderedFileName(record, name));
  const ownership =
    record.installedPath === expectedDestination ? "owned" : "foreign";

  return { ownership, name, home, expectedDestination };
}

/**
 * Bind a legacy or current manifest to the supplied config without changing
 * any installed output. Legacy record names are materialized so a caller can
 * persist the returned manifest only after its own migration decision.
 */
export function normalizeManifestIdentity(
  manifest: Manifest,
  config: ResolvedConfig,
): NormalizedManifestIdentity {
  const boundary = normalizeManifestBoundary(config);
  if (manifest.boundary) {
    assertManifestBoundaryMatches(manifest.boundary, boundary);
  }

  const classifications = manifest.records.map((record) =>
    classifyManagedRecord(record, boundary),
  );
  const records = manifest.records.map((record, index) => ({
    ...record,
    name: classifications[index].name,
  }));

  return {
    boundary,
    records: classifications,
    manifest: { ...manifest, boundary, records },
  };
}

function targetHome(
  record: Pick<ManagedRecord, "target" | "type">,
  boundary: ManifestBoundary,
): string {
  if (record.target === "claude") {
    return record.type === "skill"
      ? boundary.claudeSkillsHome
      : boundary.claudeAgentsHome;
  }
  return record.type === "skill"
    ? boundary.codexSkillsHome
    : boundary.codexAgentsHome;
}

function deriveLegacyRecordName(record: ManagedRecord, home: string): string {
  const relativePath = path.relative(home, record.installedPath);
  if (
    relativePath !== "" &&
    !relativePath.startsWith(`..${path.sep}`) &&
    relativePath !== ".." &&
    !path.isAbsolute(relativePath) &&
    relativePath.includes(path.sep)
  ) {
    throw new ManifestIdentityError(
      "Cannot derive a record name from a nested installed path",
    );
  }
  const installedBaseName = path.basename(record.installedPath);
  if (installedBaseName === "" || installedBaseName === ".") {
    throw new ManifestIdentityError(
      "Cannot derive a record name from an empty path",
    );
  }

  if (record.type === "skill") return installedBaseName;

  const suffix = agentSuffix(record.target);
  if (!installedBaseName.endsWith(suffix)) {
    throw new ManifestIdentityError(
      `Cannot derive ${record.target} agent name: installed path must end in ${suffix}`,
    );
  }

  const name = installedBaseName.slice(0, -suffix.length);
  if (name.length === 0) {
    throw new ManifestIdentityError("Cannot derive an empty record name");
  }
  return name;
}

function assertNoTraversalSegments(installedPath: string): void {
  if (installedPath.split(/[\\/]+/).includes("..")) {
    throw new ManifestIdentityError(
      "Manifest installed path must not contain traversal segments",
    );
  }
}

function assertRecordName(name: string, record: ManagedRecord): void {
  if (
    name.length === 0 ||
    name === "." ||
    name === ".." ||
    name.includes("/") ||
    name.includes("\\") ||
    path.basename(name) !== name
  ) {
    throw new ManifestIdentityError(
      `Manifest record name must be one direct-child name: ${JSON.stringify(name)}`,
    );
  }

  if (record.type === "agent" && name.endsWith(agentSuffix(record.target))) {
    throw new ManifestIdentityError(
      `Manifest ${record.target} agent name must not include ${agentSuffix(record.target)}`,
    );
  }
}

function renderedFileName(
  record: Pick<ManagedRecord, "target" | "type">,
  name: string,
): string {
  return record.type === "skill"
    ? name
    : `${name}${agentSuffix(record.target)}`;
}

function agentSuffix(target: ManagedRecord["target"]): ".md" | ".toml" {
  return target === "claude" ? ".md" : ".toml";
}
